[package]
authors     = ["Parity Technologies <admin@parity.io>"]
description = "Authority discovery primitives"
edition     = "2018"
homepage    = "https://substrate.dev"
license     = "Apache-2.0"
name        = "sp-authority-discovery"
readme      = "README.md"
repository  = "https://github.com/paritytech/substrate/"
version     = "4.0.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec                 = { package = "parity-scale-codec", default-features = false, version = "2.0.0" }
sp-api                = { version = "4.0.0-dev", default-features = false, path = "../api" }
sp-application-crypto = { version = "4.0.0-dev", default-features = false, path = "../application-crypto" }
sp-runtime            = { version = "4.0.0-dev", default-features = false, path = "../runtime" }
sp-std                = { version = "4.0.0-dev", default-features = false, path = "../std" }

[features]
default = ["std"]
std = [
	"sp-application-crypto/std",
	"codec/std",
	"sp-std/std",
	"sp-api/std",
	"sp-runtime/std",
]
