[package]
authors       = ["Parity Technologies <admin@parity.io>"]
description   = "Keyring support code for the runtime. A set of test accounts."
documentation = "https://docs.rs/sp-keyring"
edition       = "2018"
homepage      = "https://substrate.dev"
license       = "Apache-2.0"
name          = "sp-keyring"
readme        = "README.md"
repository    = "https://github.com/paritytech/substrate/"
version       = "4.0.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]


[dependencies]
lazy_static = "1.4.0"

sp-core    = { version = "4.0.0-dev", path = "../core" }
sp-runtime = { version = "4.0.0-dev", path = "../runtime" }
strum      = { version = "0.20.0", features = ["derive"] }
