[package]
authors     = ["Parity Technologies <admin@parity.io>"]
description = "FRAME sessions pallet benchmarking"
edition     = "2018"
homepage    = "https://substrate.dev"
license     = "Apache-2.0"
name        = "pallet-session-benchmarking"
readme      = "README.md"
repository  = "https://github.com/paritytech/substrate/"
version     = "4.0.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
rand = { version = "0.7.2", default-features = false }

frame-benchmarking = { version = "4.0.0-dev", default-features = false, path = "../../benchmarking" }
frame-support      = { version = "4.0.0-dev", default-features = false, path = "../../support" }
frame-system       = { version = "4.0.0-dev", default-features = false, path = "../../system" }
pallet-session     = { version = "4.0.0-dev", default-features = false, path = "../../session" }
pallet-staking     = { version = "4.0.0-dev", default-features = false, features = ["runtime-benchmarks"], path = "../../staking" }
sp-runtime         = { version = "4.0.0-dev", default-features = false, path = "../../../primitives/runtime" }
sp-session         = { version = "4.0.0-dev", default-features = false, path = "../../../primitives/session" }
sp-std             = { version = "4.0.0-dev", default-features = false, path = "../../../primitives/std" }

[dev-dependencies]
codec                           = { package = "parity-scale-codec", version = "2.0.0", features = ["derive"] }
frame-election-provider-support = { version = "4.0.0-dev", path = "../../election-provider-support" }
pallet-balances                 = { version = "4.0.0-dev", path = "../../balances" }
pallet-staking-reward-curve     = { version = "4.0.0-dev", path = "../../staking/reward-curve" }
pallet-timestamp                = { version = "4.0.0-dev", path = "../../timestamp" }
sp-core                         = { version = "4.0.0-dev", path = "../../../primitives/core" }
sp-io                           = { version = "4.0.0-dev", path = "../../../primitives/io" }

[features]
default = ["std"]
std = [
	"sp-std/std",
	"sp-session/std",
	"sp-runtime/std",
	"frame-system/std",
	"frame-benchmarking/std",
	"frame-support/std",
	"pallet-staking/std",
	"pallet-session/std",
]
