[package]
authors     = ["Parity Technologies <admin@parity.io>"]
description = "Generic Transaction Pool"
edition     = "2018"
homepage    = "https://substrate.dev"
license     = "GPL-3.0-or-later WITH Classpath-exception-2.0"
name        = "sc-transaction-graph"
readme      = "README.md"
repository  = "https://github.com/paritytech/substrate/"
version     = "4.0.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
derive_more     = "0.99.2"
futures         = "0.3.9"
linked-hash-map = "0.5.4"
log             = "0.4.8"
parking_lot     = "0.11.1"
retain_mut      = "0.1.3"
thiserror       = "1.0.21"

parity-util-mem     = { version = "0.10.0", default-features = false, features = ["primitive-types"] }
serde               = { version = "1.0.101", features = ["derive"] }
sp-blockchain       = { version = "4.0.0-dev", path = "../../../primitives/blockchain" }
sp-core             = { version = "4.0.0-dev", path = "../../../primitives/core" }
sp-runtime          = { version = "4.0.0-dev", path = "../../../primitives/runtime" }
sp-transaction-pool = { version = "4.0.0-dev", path = "../../../primitives/transaction-pool" }
sp-utils            = { version = "4.0.0-dev", path = "../../../primitives/utils" }

[dev-dependencies]
assert_matches = "1.3.0"
criterion      = "0.3"

codec                  = { package = "parity-scale-codec", version = "2.0.0" }
substrate-test-runtime = { version = "2.0.0", path = "../../../test-utils/runtime" }

[[bench]]
harness = false
name    = "basics"
