[package]
authors     = ["Parity Technologies <admin@parity.io>"]
description = "FRAME system module"
edition     = "2018"
homepage    = "https://substrate.dev"
license     = "Apache-2.0"
name        = "frame-system"
readme      = "README.md"
repository  = "https://github.com/paritytech/substrate/"
version     = "4.0.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
log   = { version = "0.4.14", default-features = false }
serde = { version = "1.0.126", optional = true, features = ["derive"] }

codec         = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
frame-support = { version = "4.0.0-dev", default-features = false, path = "../support" }
sp-core       = { version = "4.0.0-dev", default-features = false, path = "../../primitives/core" }
sp-io         = { version = "4.0.0-dev", path = "../../primitives/io", default-features = false }
sp-runtime    = { version = "4.0.0-dev", default-features = false, path = "../../primitives/runtime" }
sp-std        = { version = "4.0.0-dev", default-features = false, path = "../../primitives/std" }
sp-version    = { version = "4.0.0-dev", default-features = false, path = "../../primitives/version" }

[dev-dependencies]
criterion = "0.3.3"

sp-externalities              = { version = "0.10.0-dev", path = "../../primitives/externalities" }
substrate-test-runtime-client = { version = "2.0.0", path = "../../test-utils/runtime/client" }

[features]
default = ["std"]
runtime-benchmarks = [
	"sp-runtime/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
]
std = [
	"serde",
	"codec/std",
	"sp-core/std",
	"sp-std/std",
	"sp-io/std",
	"frame-support/std",
	"sp-runtime/std",
	"sp-version/std",
	"log/std",
]
try-runtime = ["frame-support/try-runtime"]

[[bench]]
harness = false
name    = "bench"
