[package]
authors     = ["Parity Technologies <admin@parity.io>"]
description = "Utility for building WASM binaries"
edition     = "2018"
homepage    = "https://substrate.dev"
license     = "Apache-2.0"
name        = "substrate-wasm-builder"
readme      = "README.md"
repository  = "https://github.com/paritytech/substrate/"
version     = "5.0.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
ansi_term      = "0.12.1"
build-helper   = "0.1.1"
cargo_metadata = "0.13.1"
tempfile       = "3.1.0"
toml           = "0.5.4"
walkdir        = "2.3.2"
wasm-gc-api    = "0.1.11"

sp-maybe-compressed-blob = { version = "4.0.0-dev", path = "../../primitives/maybe-compressed-blob" }
