[package]
authors     = ["Parity Technologies <admin@parity.io>"]
description = "Substrate RPC servers."
edition     = "2018"
homepage    = "https://substrate.dev"
license     = "GPL-3.0-or-later WITH Classpath-exception-2.0"
name        = "sc-rpc-server"
readme      = "README.md"
repository  = "https://github.com/paritytech/substrate/"
version     = "4.0.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
futures      = "0.3.16"
jsonrpc-core = "18.0.0"
log          = "0.4.8"
serde_json   = "1.0.41"

prometheus-endpoint = { package = "substrate-prometheus-endpoint", path = "../../utils/prometheus", version = "0.9.0" }
pubsub              = { package = "jsonrpc-pubsub", version = "18.0.0" }

[target.'cfg(not(target_os = "unknown"))'.dependencies]
http = { package = "jsonrpc-http-server", version = "18.0.0" }
ipc  = { package = "jsonrpc-ipc-server", version = "18.0.0" }
ws   = { package = "jsonrpc-ws-server", version = "18.0.0" }
