[package]
authors       = ["Parity Technologies <admin@parity.io>"]
description   = "I/O for Substrate runtimes"
documentation = "https://docs.rs/sp-io"
edition       = "2018"
homepage      = "https://substrate.dev"
license       = "Apache-2.0"
name          = "sp-io"
readme        = "README.md"
repository    = "https://github.com/paritytech/substrate/"
version       = "4.0.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]


[dependencies]
futures      = { version = "0.3.1", features = ["thread-pool"], optional = true }
hash-db      = { version = "0.15.2", default-features = false }
libsecp256k1 = { version = "0.6", optional = true }
log          = { version = "0.4.8", optional = true }
parking_lot  = { version = "0.11.1", optional = true }
tracing      = { version = "0.1.25", default-features = false }
tracing-core = { version = "0.1.17", default-features = false }

codec                    = { package = "parity-scale-codec", version = "2.0.0", default-features = false }
sp-core                  = { version = "4.0.0-dev", default-features = false, path = "../core" }
sp-externalities         = { version = "0.10.0-dev", optional = true, path = "../externalities" }
sp-keystore              = { version = "0.10.0-dev", default-features = false, optional = true, path = "../keystore" }
sp-maybe-compressed-blob = { version = "4.0.0-dev", optional = true, path = "../maybe-compressed-blob" }
sp-runtime-interface     = { version = "4.0.0-dev", default-features = false, path = "../runtime-interface" }
sp-state-machine         = { version = "0.10.0-dev", optional = true, path = "../state-machine" }
sp-std                   = { version = "4.0.0-dev", default-features = false, path = "../std" }
sp-tracing               = { version = "4.0.0-dev", default-features = false, path = "../tracing" }
sp-trie                  = { version = "4.0.0-dev", optional = true, path = "../trie" }
sp-wasm-interface        = { version = "4.0.0-dev", path = "../wasm-interface", default-features = false }

[features]
default = ["std"]
std = [
	"sp-core/std",
	"sp-keystore",
	"codec/std",
	"sp-std/std",
	"hash-db/std",
	"sp-trie",
	"sp-state-machine",
	"libsecp256k1",
	"sp-runtime-interface/std",
	"sp-externalities",
	"sp-wasm-interface/std",
	"sp-maybe-compressed-blob",
	"sp-tracing/std",
	"tracing/std",
	"tracing-core/std",
	"log",
	"futures",
	"parking_lot",
]

with-tracing = [
	"sp-tracing/with-tracing",
]

# These two features are used for `no_std` builds for the environments which already provides
# `#[panic_handler]`, `#[alloc_error_handler]` and `#[global_allocator]`.
#
# For the regular wasm runtime builds those are not used.
disable_allocator     = []
disable_oom           = []
disable_panic_handler = []
