[package]
authors     = ["Parity Technologies <admin@parity.io>"]
description = "Macros to derive chain spec extension traits implementation."
edition     = "2018"
homepage    = "https://substrate.dev"
license     = "GPL-3.0-or-later WITH Classpath-exception-2.0"
name        = "sc-chain-spec-derive"
repository  = "https://github.com/paritytech/substrate/"
version     = "4.0.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
proc-macro = true

[dependencies]
proc-macro-crate = "1.0.0"
proc-macro2      = "1.0.28"
quote            = "1.0.3"
syn              = "1.0.58"

[dev-dependencies]
