[package]
authors       = ["Parity Technologies <admin@parity.io>"]
description   = "Keystore primitives."
documentation = "https://docs.rs/sp-core"
edition       = "2018"
homepage      = "https://substrate.dev"
license       = "Apache-2.0"
name          = "sp-keystore"
repository    = "https://github.com/paritytech/substrate/"
version       = "0.10.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
async-trait = "0.1.50"
derive_more = "0.99.2"
futures     = { version = "0.3.1" }
merlin      = { version = "2.0", default-features = false }
parking_lot = { version = "0.11.1", default-features = false }
serde       = { version = "1.0", optional = true }

codec            = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
schnorrkel       = { version = "0.9.1", features = ["preaudit_deprecated", "u64_backend"], default-features = false }
sp-core          = { version = "4.0.0-dev", path = "../core" }
sp-externalities = { version = "0.10.0-dev", path = "../externalities", default-features = false }

[dev-dependencies]
rand        = "0.7.2"
rand_chacha = "0.2.2"


[features]
default = ["std"]
std = [
	"serde",
	"schnorrkel/std",
]
