[package]
authors     = ["Parity Technologies <admin@parity.io>"]
description = "Helper macros for Substrate's client CLI"
edition     = "2018"
homepage    = "https://substrate.dev"
license     = "Apache-2.0"
name        = "sc-tracing-proc-macro"
repository  = "https://github.com/paritytech/substrate/"
version     = "4.0.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
proc-macro = true

[dependencies]
proc-macro-crate = "1.0.0"
proc-macro2      = "1.0.28"
quote            = { version = "1.0.3", features = ["proc-macro"] }
syn              = { version = "1.0.58", features = ["proc-macro", "full", "extra-traits", "parsing"] }
