[package]
authors       = ["Parity Technologies <admin@parity.io>"]
description   = "Types and traits for interfacing between the host and the wasm runtime."
documentation = "https://docs.rs/sp-wasm-interface"
edition       = "2018"
homepage      = "https://substrate.dev"
license       = "Apache-2.0"
name          = "sp-wasm-interface"
readme        = "README.md"
repository    = "https://github.com/paritytech/substrate/"
version       = "4.0.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
impl-trait-for-tuples = "0.2.1"
wasmi                 = { version = "0.9.0", optional = true }

codec  = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
sp-std = { version = "4.0.0-dev", path = "../std", default-features = false }

[features]
default = ["std"]
std     = ["wasmi", "sp-std/std", "codec/std"]
