[package]
authors     = ["Parity Technologies <admin@parity.io>"]
description = "A RPC handler to create sync states for light clients."
edition     = "2018"
homepage    = "https://substrate.dev"
license     = "Apache-2.0"
name        = "sc-sync-state-rpc"
readme      = "README.md"
repository  = "https://github.com/paritytech/substrate/"
version     = "0.10.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
jsonrpc-core        = "18.0.0"
jsonrpc-core-client = "18.0.0"
jsonrpc-derive      = "18.0.0"
serde               = { version = "1.0.126", features = ["derive"] }
serde_json          = "1.0.58"
thiserror           = "1.0.21"

codec               = { package = "parity-scale-codec", version = "2.0.0" }
sc-chain-spec       = { version = "4.0.0-dev", path = "../chain-spec" }
sc-client-api       = { version = "4.0.0-dev", path = "../api" }
sc-consensus-babe   = { version = "0.10.0-dev", path = "../consensus/babe" }
sc-consensus-epochs = { version = "0.10.0-dev", path = "../consensus/epochs" }
sc-finality-grandpa = { version = "0.10.0-dev", path = "../finality-grandpa" }
sc-rpc-api          = { version = "0.10.0-dev", path = "../rpc-api" }
sp-blockchain       = { version = "4.0.0-dev", path = "../../primitives/blockchain" }
sp-runtime          = { version = "4.0.0-dev", path = "../../primitives/runtime" }
