[package]
authors       = ["Parity Technologies <admin@parity.io>"]
description   = "Macro for defining a runtime version."
documentation = "https://docs.rs/sp-api-proc-macro"
edition       = "2018"
homepage      = "https://substrate.dev"
license       = "Apache-2.0"
name          = "sp-version-proc-macro"
repository    = "https://github.com/paritytech/substrate/"
version       = "4.0.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.28"
quote       = "1.0.3"
syn         = { version = "1.0.58", features = ["full", "fold", "extra-traits", "visit"] }

codec = { package = "parity-scale-codec", version = "2.0.0", features = ["derive"] }

[dev-dependencies]
sp-version = { version = "4.0.0-dev", path = ".." }
