[package]
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
name    = "test-runner-example"
publish = false
version = "0.1.0"

[dependencies]
test-runner = { path = "../../../test-utils/test-runner" }

frame-benchmarking         = { path = "../../../frame/benchmarking" }
frame-system               = { path = "../../../frame/system" }
pallet-transaction-payment = { path = "../../../frame/transaction-payment" }

node-cli        = { path = "../cli" }
node-primitives = { path = "../primitives" }
node-runtime    = { path = "../runtime" }

grandpa                  = { package = "sc-finality-grandpa", path = "../../../client/finality-grandpa" }
sc-consensus             = { path = "../../../client/consensus/common" }
sc-consensus-babe        = { path = "../../../client/consensus/babe" }
sc-consensus-manual-seal = { path = "../../../client/consensus/manual-seal" }
sc-executor              = { path = "../../../client/executor" }
sc-service               = { default-features = false, path = "../../../client/service" }
sp-consensus-babe        = { path = "../../../primitives/consensus/babe" }

sp-keyring = { path = "../../../primitives/keyring" }
sp-runtime = { path = "../../../primitives/runtime" }
