[package]
authors     = ["Parity Technologies <admin@parity.io>"]
description = "Endpoint to expose Prometheus metrics"
edition     = "2018"
homepage    = "https://substrate.dev"
license     = "Apache-2.0"
name        = "substrate-prometheus-endpoint"
readme      = "README.md"
repository  = "https://github.com/paritytech/substrate/"
version     = "0.9.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
derive_more  = "0.99"
futures-util = { version = "0.3.1", default-features = false, features = ["io"] }
log          = "0.4.8"
prometheus   = { version = "0.11.0", default-features = false }

[target.'cfg(not(target_os = "unknown"))'.dependencies]
async-std = { version = "1.6.5", features = ["unstable"] }
hyper     = { version = "0.14.11", default-features = false, features = ["http1", "server", "tcp"] }
tokio     = "1.10"

[dev-dependencies]
hyper = { version = "0.14.11", features = ["client"] }
tokio = { version = "1.10", features = ["rt-multi-thread"] }
