[package]
authors     = ["Parity Technologies <admin@parity.io>"]
description = "Transaction pool client facing API."
edition     = "2018"
homepage    = "https://substrate.dev"
license     = "GPL-3.0-or-later WITH Classpath-exception-2.0"
name        = "sc-transaction-pool-api"
repository  = "https://github.com/paritytech/substrate/"
version     = "4.0.0-dev"

[dependencies]
derive_more = { version = "0.99.11" }
futures     = { version = "0.3.1" }
log         = { version = "0.4.8" }
serde       = { version = "1.0.126", features = ["derive"] }
thiserror   = { version = "1.0.21" }

sp-blockchain = { version = "4.0.0-dev", path = "../../../primitives/blockchain" }
sp-runtime    = { version = "4.0.0-dev", default-features = false, path = "../../../primitives/runtime" }
