[package]
authors     = ["Parity Technologies <admin@parity.io>"]
description = "Primitives for Aura consensus"
edition     = "2018"
homepage    = "https://substrate.dev"
license     = "Apache-2.0"
name        = "sp-consensus-aura"
readme      = "README.md"
repository  = "https://github.com/paritytech/substrate/"
version     = "0.10.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
async-trait = { version = "0.1.50", optional = true }

codec                 = { package = "parity-scale-codec", version = "2.0.0", default-features = false }
sp-api                = { version = "4.0.0-dev", default-features = false, path = "../../api" }
sp-application-crypto = { version = "4.0.0-dev", default-features = false, path = "../../application-crypto" }
sp-consensus          = { version = "0.10.0-dev", path = "../common", optional = true }
sp-consensus-slots    = { version = "0.10.0-dev", default-features = false, path = "../slots" }
sp-inherents          = { version = "4.0.0-dev", default-features = false, path = "../../inherents" }
sp-runtime            = { version = "4.0.0-dev", default-features = false, path = "../../runtime" }
sp-std                = { version = "4.0.0-dev", default-features = false, path = "../../std" }
sp-timestamp          = { version = "4.0.0-dev", default-features = false, path = "../../timestamp" }

[features]
default = ["std"]
std = [
	"sp-application-crypto/std",
	"codec/std",
	"sp-std/std",
	"sp-api/std",
	"sp-runtime/std",
	"sp-inherents/std",
	"sp-timestamp/std",
	"sp-consensus-slots/std",
	"sp-consensus",
	"async-trait",
]
