[package]
authors     = ["Parity Technologies <admin@parity.io>"]
description = "Storage chain pallet"
edition     = "2018"
homepage    = "https://substrate.dev"
license     = "Unlicense"
name        = "pallet-transaction-storage"
readme      = "README.md"
repository  = "https://github.com/paritytech/substrate/"
version     = "4.0.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
hex-literal = { version = "0.3.1", optional = true }
serde       = { version = "1.0.126", optional = true }

codec                        = { package = "parity-scale-codec", version = "2.0.0", default-features = false }
frame-benchmarking           = { version = "4.0.0-dev", default-features = false, path = "../benchmarking", optional = true }
frame-support                = { version = "4.0.0-dev", default-features = false, path = "../support" }
frame-system                 = { version = "4.0.0-dev", default-features = false, path = "../system" }
pallet-balances              = { version = "4.0.0-dev", default-features = false, path = "../balances" }
sp-inherents                 = { version = "4.0.0-dev", default-features = false, path = "../../primitives/inherents" }
sp-io                        = { version = "4.0.0-dev", default-features = false, path = "../../primitives/io" }
sp-runtime                   = { version = "4.0.0-dev", default-features = false, path = "../../primitives/runtime" }
sp-std                       = { version = "4.0.0-dev", default-features = false, path = "../../primitives/std" }
sp-transaction-storage-proof = { version = "4.0.0-dev", default-features = false, path = "../../primitives/transaction-storage-proof" }

[dev-dependencies]
sp-core                      = { version = "4.0.0-dev", path = "../../primitives/core", default-features = false }
sp-transaction-storage-proof = { version = "4.0.0-dev", default-features = true, path = "../../primitives/transaction-storage-proof" }

[features]
default = ["std"]
runtime-benchmarks = ["frame-benchmarking", "hex-literal"]
std = [
	"serde",
	"codec/std",
	"sp-runtime/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-balances/std",
	"sp-io/std",
	"sp-std/std",
	"sp-inherents/std",
]
