[package]
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
name    = "test-runner"
publish = false
version = "0.9.0"

[dependencies]
futures = "0.3.16"
log     = "0.4.8"
tokio   = { version = "1.10", features = ["signal"] }
# Calling RPC
jsonrpc-core = "18.0"
num-traits   = "0.2.14"

# client deps
grandpa                 = { package = "sc-finality-grandpa", path = "../../client/finality-grandpa" }
manual-seal             = { package = "sc-consensus-manual-seal", path = "../../client/consensus/manual-seal" }
sc-basic-authorship     = { path = "../../client/basic-authorship" }
sc-cli                  = { path = "../../client/cli" }
sc-client-api           = { path = "../../client/api" }
sc-consensus            = { path = "../../client/consensus/common" }
sc-consensus-babe       = { path = "../../client/consensus/babe" }
sc-executor             = { path = "../../client/executor" }
sc-informant            = { path = "../../client/informant" }
sc-network              = { path = "../../client/network" }
sc-rpc                  = { path = "../../client/rpc" }
sc-rpc-server           = { path = "../../client/rpc-servers" }
sc-service              = { path = "../../client/service" }
sc-transaction-pool     = { path = "../../client/transaction-pool" }
sc-transaction-pool-api = { path = "../../client/transaction-pool/api" }
sp-consensus-babe       = { path = "../../primitives/consensus/babe" }
sp-finality-grandpa     = { path = "../../primitives/finality-grandpa" }

# primitive deps
sp-api              = { path = "../../primitives/api" }
sp-block-builder    = { path = "../../primitives/block-builder" }
sp-blockchain       = { path = "../../primitives/blockchain" }
sp-consensus        = { path = "../../primitives/consensus/common" }
sp-core             = { path = "../../primitives/core" }
sp-inherents        = { path = "../../primitives/inherents" }
sp-keyring          = { path = "../../primitives/keyring" }
sp-offchain         = { path = "../../primitives/offchain" }
sp-runtime          = { path = "../../primitives/runtime" }
sp-session          = { path = "../../primitives/session" }
sp-transaction-pool = { path = "../../primitives/transaction-pool" }

sp-externalities     = { path = "../../primitives/externalities" }
sp-runtime-interface = { path = "../../primitives/runtime-interface" }
sp-state-machine     = { path = "../../primitives/state-machine" }
sp-wasm-interface    = { path = "../../primitives/wasm-interface" }

# pallets
frame-system = { path = "../../frame/system" }
