[package]
authors       = ["Parity Technologies <admin@parity.io>"]
description   = "Minimal fixed point arithmetic primitives and types for runtime."
documentation = "https://docs.rs/sp-arithmetic"
edition       = "2018"
homepage      = "https://substrate.dev"
license       = "Apache-2.0"
name          = "sp-arithmetic"
readme        = "README.md"
repository    = "https://github.com/paritytech/substrate/"
version       = "4.0.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]


[dependencies]
integer-sqrt      = "0.1.2"
num-traits        = { version = "0.2.8", default-features = false }
serde             = { version = "1.0.126", optional = true, features = ["derive"] }
static_assertions = "1.1.0"

codec           = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
sp-debug-derive = { version = "3.0.0", default-features = false, path = "../debug-derive" }
sp-std          = { version = "4.0.0-dev", default-features = false, path = "../std" }

[dev-dependencies]
criterion       = "0.3"
primitive-types = "0.10.0"
rand            = "0.7.2"

[features]
default = ["std"]
std = [
	"codec/std",
	"num-traits/std",
	"sp-std/std",
	"serde",
	"sp-debug-derive/std",
]

[[bench]]
harness = false
name    = "bench"
