[package]
authors     = ["Parity Technologies <admin@parity.io>"]
description = "NPoS election algorithm primitives"
edition     = "2018"
homepage    = "https://substrate.dev"
license     = "Apache-2.0"
name        = "sp-npos-elections"
readme      = "README.md"
repository  = "https://github.com/paritytech/substrate/"
version     = "4.0.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
serde = { version = "1.0.126", optional = true, features = ["derive"] }

codec                           = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
sp-arithmetic                   = { version = "4.0.0-dev", default-features = false, path = "../arithmetic" }
sp-core                         = { version = "4.0.0-dev", default-features = false, path = "../core" }
sp-npos-elections-solution-type = { version = "4.0.0-dev", path = "./solution-type" }
sp-std                          = { version = "4.0.0-dev", default-features = false, path = "../std" }

[dev-dependencies]
rand = "0.7.3"

sp-runtime           = { version = "4.0.0-dev", path = "../runtime" }
substrate-test-utils = { version = "4.0.0-dev", path = "../../test-utils" }

[features]
bench = []
default = ["std"]
std = [
	"codec/std",
	"serde",
	"sp-std/std",
	"sp-arithmetic/std",
	"sp-core/std",
]
