[package]
authors       = ["Parity Technologies <admin@parity.io>"]
description   = "Handling of blobs, usually Wasm code, which may be compresed"
documentation = "https://docs.rs/sp-maybe-compressed-blob"
edition       = "2018"
homepage      = "https://substrate.dev"
license       = "Apache-2.0"
name          = "sp-maybe-compressed-blob"
readme        = "README.md"
repository    = "https://github.com/paritytech/substrate/"
version       = "4.0.0-dev"

[target.'cfg(not(target_os = "unknown"))'.dependencies]
zstd = { version = "0.6.0", default-features = false }

[target.'cfg(target_os = "unknown")'.dependencies]
ruzstd = { version = "0.2.2" }
