[package]
authors     = ["Parity Technologies <admin@parity.io>"]
description = "Substrate test utilities macros"
edition     = "2018"
homepage    = "https://substrate.dev"
license     = "Apache-2.0"
name        = "substrate-test-utils-derive"
repository  = "https://github.com/paritytech/substrate/"
version     = "0.10.0-dev"

[dependencies]
proc-macro-crate = "1.0.0"
proc-macro2      = "1.0.28"
quote            = "1.0.6"
syn              = { version = "1.0.58", features = ["full"] }

[lib]
proc-macro = true
