[package]
authors     = ["Parity Technologies <admin@parity.io>"]
description = "I/O for Substrate runtimes"
edition     = "2018"
homepage    = "https://substrate.dev"
license     = "Apache-2.0"
name        = "sp-utils"
readme      = "README.md"
repository  = "https://github.com/paritytech/substrate/"
version     = "4.0.0-dev"

[dependencies]
futures       = "0.3.9"
futures-timer = "3.0.2"
lazy_static   = "1.4.0"
prometheus    = { version = "0.11.0", default-features = false }

[features]
default = ["metered"]
metered = []
