[package]
authors       = ["Parity Technologies <admin@parity.io>"]
description   = "Provides facilities for generating application specific crypto wrapper types."
documentation = "https://docs.rs/sp-application-crypto"
edition       = "2018"
homepage      = "https://substrate.dev"
license       = "Apache-2.0"
name          = "sp-application-crypto"
readme        = "README.md"
repository    = "https://github.com/paritytech/substrate/"
version       = "4.0.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]


[dependencies]
serde = { version = "1.0.126", optional = true, features = ["derive"] }

codec   = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
sp-core = { version = "4.0.0-dev", default-features = false, path = "../core" }
sp-io   = { version = "4.0.0-dev", default-features = false, path = "../io" }
sp-std  = { version = "4.0.0-dev", default-features = false, path = "../std" }

[features]
default = ["std"]
std = [
	"full_crypto",
	"sp-core/std",
	"codec/std",
	"serde",
	"sp-std/std",
	"sp-io/std",
]

# This feature enables all crypto primitives for `no_std` builds like microcontrollers
# or Intel SGX.
# For the regular wasm runtime builds this should not be used.
full_crypto = [
	"sp-core/full_crypto",
	# Don't add `panic_handler` and `alloc_error_handler` since they are expected to be provided
	# by the user anyway.
	"sp-io/disable_panic_handler",
	"sp-io/disable_oom",
]
