[package]
authors       = ["Parity Technologies <admin@parity.io>"]
description   = "Gossiping for the Substrate network protocol"
documentation = "https://docs.rs/sc-network-gossip"
edition       = "2018"
homepage      = "https://substrate.dev"
license       = "GPL-3.0-or-later WITH Classpath-exception-2.0"
name          = "sc-network-gossip"
readme        = "README.md"
repository    = "https://github.com/paritytech/substrate/"
version       = "0.10.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]


[dependencies]
futures       = "0.3.9"
futures-timer = "3.0.1"
log           = "0.4.8"
lru           = "0.6.5"
tracing       = "0.1.25"

libp2p              = { version = "0.39.1", default-features = false }
prometheus-endpoint = { package = "substrate-prometheus-endpoint", version = "0.9.0", path = "../../utils/prometheus" }
sc-network          = { version = "0.10.0-dev", path = "../network" }
sp-runtime          = { version = "4.0.0-dev", path = "../../primitives/runtime" }

[dev-dependencies]
async-std  = "1.6.5"
quickcheck = "1.0.3"

substrate-test-runtime-client = { version = "2.0.0", path = "../../test-utils/runtime/client" }
