[package]
authors     = ["Parity Technologies <admin@parity.io>"]
description = "Generic uncle inclusion utilities for consensus"
edition     = "2018"
homepage    = "https://substrate.dev"
license     = "GPL-3.0-or-later WITH Classpath-exception-2.0"
name        = "sc-consensus-uncles"
readme      = "README.md"
repository  = "https://github.com/paritytech/substrate/"
version     = "0.10.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
thiserror = "1.0.21"

sc-client-api = { version = "4.0.0-dev", path = "../../api" }
sp-authorship = { version = "4.0.0-dev", path = "../../../primitives/authorship" }
sp-runtime    = { version = "4.0.0-dev", path = "../../../primitives/runtime" }
