[package]
authors       = ["Parity Technologies <admin@parity.io>"]
description   = "Transaction pool runtime facing API."
documentation = "https://docs.rs/sp-transaction-pool"
edition       = "2018"
homepage      = "https://substrate.dev"
license       = "Apache-2.0"
name          = "sp-transaction-pool"
readme        = "README.md"
repository    = "https://github.com/paritytech/substrate/"
version       = "4.0.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sp-api     = { version = "4.0.0-dev", default-features = false, path = "../api" }
sp-runtime = { version = "4.0.0-dev", default-features = false, path = "../runtime" }

[features]
default = ["std"]
std = [
	"sp-api/std",
	"sp-runtime/std",
]
