[package]
authors       = ["Parity Technologies <admin@parity.io>"]
description   = "BABE consensus algorithm for substrate"
documentation = "https://docs.rs/sc-consensus-babe"
edition       = "2018"
homepage      = "https://substrate.dev"
license       = "GPL-3.0-or-later WITH Classpath-exception-2.0"
name          = "sc-consensus-babe"
readme        = "README.md"
repository    = "https://github.com/paritytech/substrate/"
version       = "0.10.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
async-trait  = "0.1.50"
derive_more  = "0.99.2"
futures      = "0.3.9"
log          = "0.4.8"
merlin       = "2.0"
num-bigint   = "0.2.3"
num-rational = "0.2.2"
num-traits   = "0.2.8"
parking_lot  = "0.11.1"
rand         = "0.7.2"
retain_mut   = "0.1.3"
serde        = { version = "1.0.126", features = ["derive"] }

codec                 = { package = "parity-scale-codec", version = "2.0.0", features = ["derive"] }
fork-tree             = { version = "3.0.0", path = "../../../utils/fork-tree" }
prometheus-endpoint   = { package = "substrate-prometheus-endpoint", path = "../../../utils/prometheus", version = "0.9.0" }
sc-client-api         = { version = "4.0.0-dev", path = "../../api" }
sc-consensus          = { version = "0.10.0-dev", path = "../../../client/consensus/common" }
sc-consensus-epochs   = { version = "0.10.0-dev", path = "../epochs" }
sc-consensus-slots    = { version = "0.10.0-dev", path = "../slots" }
sc-keystore           = { version = "4.0.0-dev", path = "../../keystore" }
sc-telemetry          = { version = "4.0.0-dev", path = "../../telemetry" }
schnorrkel            = { version = "0.9.1", features = ["preaudit_deprecated"] }
sp-api                = { version = "4.0.0-dev", path = "../../../primitives/api" }
sp-application-crypto = { version = "4.0.0-dev", path = "../../../primitives/application-crypto" }
sp-block-builder      = { version = "4.0.0-dev", path = "../../../primitives/block-builder" }
sp-blockchain         = { version = "4.0.0-dev", path = "../../../primitives/blockchain" }
sp-consensus          = { version = "0.10.0-dev", path = "../../../primitives/consensus/common" }
sp-consensus-babe     = { version = "0.10.0-dev", path = "../../../primitives/consensus/babe" }
sp-consensus-slots    = { version = "0.10.0-dev", path = "../../../primitives/consensus/slots" }
sp-consensus-vrf      = { version = "0.10.0-dev", path = "../../../primitives/consensus/vrf" }
sp-core               = { version = "4.0.0-dev", path = "../../../primitives/core" }
sp-inherents          = { version = "4.0.0-dev", path = "../../../primitives/inherents" }
sp-io                 = { version = "4.0.0-dev", path = "../../../primitives/io" }
sp-keystore           = { version = "0.10.0-dev", path = "../../../primitives/keystore" }
sp-runtime            = { version = "4.0.0-dev", path = "../../../primitives/runtime" }
sp-version            = { version = "4.0.0-dev", path = "../../../primitives/version" }

[dev-dependencies]
rand_chacha = "0.2.2"
tempfile    = "3.1.0"

sc-block-builder              = { version = "0.10.0-dev", path = "../../block-builder" }
sc-network                    = { version = "0.10.0-dev", path = "../../network" }
sc-network-test               = { version = "0.8.0", path = "../../network/test" }
sp-timestamp                  = { version = "4.0.0-dev", path = "../../../primitives/timestamp" }
sp-tracing                    = { version = "4.0.0-dev", path = "../../../primitives/tracing" }
substrate-test-runtime-client = { version = "2.0.0", path = "../../../test-utils/runtime/client" }
