[package]
authors       = ["Parity Technologies <admin@parity.io>"]
description   = "Patricia trie stuff using a parity-scale-codec node format"
documentation = "https://docs.rs/sp-trie"
edition       = "2018"
homepage      = "https://substrate.dev"
license       = "Apache-2.0"
name          = "sp-trie"
readme        = "README.md"
repository    = "https://github.com/paritytech/substrate/"
version       = "4.0.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[[bench]]
harness = false
name    = "bench"

[dependencies]
codec     = { package = "parity-scale-codec", version = "2.0.0", default-features = false }
hash-db   = { version = "0.15.2", default-features = false }
memory-db = { version = "0.27.0", default-features = false }
sp-core   = { version = "4.0.0-dev", default-features = false, path = "../core" }
sp-std    = { version = "4.0.0-dev", default-features = false, path = "../std" }
trie-db   = { version = "0.22.6", default-features = false }
trie-root = { version = "0.16.0", default-features = false }

[dev-dependencies]
criterion   = "0.3.3"
hex-literal = "0.3.1"

sp-runtime       = { version = "4.0.0-dev", path = "../runtime" }
trie-bench       = "0.28.0"
trie-standardmap = "0.15.2"

[features]
default = ["std"]
memory-tracker = []
std = [
	"sp-std/std",
	"codec/std",
	"hash-db/std",
	"memory-db/std",
	"trie-db/std",
	"trie-root/std",
	"sp-core/std",
]
