[package]
authors       = ["Parity Technologies <admin@parity.io>"]
description   = "Version module for the Substrate runtime; Provides a function that returns the runtime version."
documentation = "https://docs.rs/sp-version"
edition       = "2018"
homepage      = "https://substrate.dev"
license       = "Apache-2.0"
name          = "sp-version"
readme        = "README.md"
repository    = "https://github.com/paritytech/substrate/"
version       = "4.0.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]


[dependencies]
impl-serde = { version = "0.3.1", optional = true }
serde      = { version = "1.0.126", optional = true, features = ["derive"] }
thiserror  = { version = "1.0.21", optional = true }

codec                 = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
parity-wasm           = { version = "0.42.2", optional = true }
sp-runtime            = { version = "4.0.0-dev", default-features = false, path = "../runtime" }
sp-std                = { version = "4.0.0-dev", default-features = false, path = "../std" }
sp-version-proc-macro = { version = "4.0.0-dev", default-features = false, path = "proc-macro" }

[features]
default = ["std"]
std = [
	"impl-serde",
	"serde",
	"codec/std",
	"sp-std/std",
	"sp-runtime/std",
	"parity-wasm",
	"thiserror",
]
