[package]
authors     = ["Parity Technologies <admin@parity.io>"]
description = "FRAME pallet to manage tips"
edition     = "2018"
homepage    = "https://substrate.dev"
license     = "Apache-2.0"
name        = "pallet-tips"
readme      = "README.md"
repository  = "https://github.com/paritytech/substrate/"
version     = "4.0.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
serde = { version = "1.0.126", optional = true, features = ["derive"] }

codec           = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
frame-support   = { version = "4.0.0-dev", default-features = false, path = "../support" }
frame-system    = { version = "4.0.0-dev", default-features = false, path = "../system" }
pallet-treasury = { version = "4.0.0-dev", default-features = false, path = "../treasury" }
sp-runtime      = { version = "4.0.0-dev", default-features = false, path = "../../primitives/runtime" }
sp-std          = { version = "4.0.0-dev", default-features = false, path = "../../primitives/std" }

frame-benchmarking = { version = "4.0.0-dev", default-features = false, path = "../benchmarking", optional = true }

[dev-dependencies]
pallet-balances = { version = "4.0.0-dev", path = "../balances" }
sp-core         = { version = "4.0.0-dev", path = "../../primitives/core" }
sp-io           = { version = "4.0.0-dev", path = "../../primitives/io" }
sp-storage      = { version = "4.0.0-dev", path = "../../primitives/storage" }

[features]
default = ["std"]
runtime-benchmarks = [
	"frame-benchmarking",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
]
std = [
	"serde",
	"codec/std",
	"sp-std/std",
	"sp-runtime/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-treasury/std",
]
try-runtime = ["frame-support/try-runtime"]
