[package]
authors     = ["Parity Technologies <admin@parity.io>"]
description = "Instrumentation primitives and macros for Substrate."
edition     = "2018"
homepage    = "https://substrate.dev"
license     = "Apache-2.0"
name        = "sp-tracing"
readme      = "README.md"
repository  = "https://github.com/paritytech/substrate/"
version     = "4.0.0-dev"

[package.metadata.docs.rs]
# let's default to wasm32
default-target = "wasm32-unknown-unknown"
# with the tracing enabled
features = ["with-tracing"]
# allowing for linux-gnu here, too, allows for `std` to show up as well
targets = ["x86_64-unknown-linux-gnu", "wasm32-unknown-unknown"]

[dependencies]
erased-serde       = { version = "0.3.9", optional = true }
log                = { version = "0.4.8", optional = true }
parking_lot        = { version = "0.10.0", optional = true }
serde              = { version = "1.0.126", optional = true }
serde_json         = { version = "1.0.41", optional = true }
slog               = { version = "2.5.2", features = ["nested-values"], optional = true }
tracing            = { version = "0.1.25", default-features = false }
tracing-core       = { version = "0.1.17", default-features = false }
tracing-subscriber = { version = "0.2.19", optional = true, features = ["tracing-log"] }

codec  = { version = "2.0.0", package = "parity-scale-codec", default-features = false, features = ["derive"] }
sp-std = { version = "4.0.0-dev", path = "../std", default-features = false }

[features]
default = ["std"]
std = [
	"with-tracing",
	"tracing/std",
	"tracing-core/std",
	"codec/std",
	"sp-std/std",
	"log",
	"tracing-subscriber",
	"parking_lot",
	"erased-serde",
	"serde",
	"serde_json",
	"slog",
]
with-tracing = ["codec/derive", "codec/full"]
