[package]
authors     = ["Parity Technologies <admin@parity.io>"]
description = "FRAME example pallet for offchain worker"
edition     = "2018"
homepage    = "https://substrate.dev"
license     = "Unlicense"
name        = "pallet-example-offchain-worker"
readme      = "README.md"
repository  = "https://github.com/paritytech/substrate/"
version     = "4.0.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec     = { package = "parity-scale-codec", version = "2.0.0", default-features = false }
lite-json = { version = "0.1", default-features = false }
log       = { version = "0.4.14", default-features = false }

frame-support = { version = "4.0.0-dev", default-features = false, path = "../support" }
frame-system  = { version = "4.0.0-dev", default-features = false, path = "../system" }
sp-core       = { version = "4.0.0-dev", default-features = false, path = "../../primitives/core" }
sp-io         = { version = "4.0.0-dev", default-features = false, path = "../../primitives/io" }
sp-keystore   = { version = "0.10.0-dev", path = "../../primitives/keystore", optional = true }
sp-runtime    = { version = "4.0.0-dev", default-features = false, path = "../../primitives/runtime" }
sp-std        = { version = "4.0.0-dev", default-features = false, path = "../../primitives/std" }

[features]
default = ["std"]
std = [
	"codec/std",
	"frame-support/std",
	"frame-system/std",
	"lite-json/std",
	"sp-core/std",
	"sp-io/std",
	"sp-keystore",
	"sp-runtime/std",
	"sp-std/std",
	"log/std",
]
try-runtime = ["frame-support/try-runtime"]
